name: Continuous Deployment Dev

on:
  push:
    branches:
      - 'master'

jobs:
  service-names:
    name: Set Service Names
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.set_service_names.outputs.services }}
    steps:
    - uses: actions/checkout@v2
    - uses: lots0logs/gh-action-get-changed-files@2.1.4
      id: changed-files
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Detect service changes
      uses: ./.github/actions/detect-service-changes
      id: service-changes
      with:
        changed-files: ${{ steps.changed-files.outputs.all }}
    - id: set_service_names
      run: |
        echo "::set-output name=services::$SERVICES"
      env:
        SERVICES: ${{ steps.service-changes.outputs.services }}
